"""production foundation baseline

Revision ID: e186e44cc682
Revises: 
Create Date: 2026-05-28 09:17:24.514807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e186e44cc682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('destinatario_correo', sa.String(length=255), nullable=False),
    sa.Column('tipo_evento', sa.String(length=40), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo_texto', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('programado_para', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("estado IN ('Pendiente', 'Enviado', 'Fallido')", name='ck_email_event_estado'),
    sa.CheckConstraint("tipo_evento IN ('meeting_created', 'meeting_updated', 'meeting_canceled', 'meeting_response', 'reminder_30', 'reminder_10')", name='ck_email_event_tipo'),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.create_index('ix_email_event_programado', ['estado', 'programado_para'], unique=False)

    op.create_table('reunion_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reunion_id', sa.Integer(), nullable=False),
    sa.Column('actor_usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(length=30), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo_evento IN ('created', 'updated', 'canceled', 'response', 'finalized')", name='ck_reunion_historial_tipo'),
    sa.ForeignKeyConstraint(['actor_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['reunion_id'], ['reuniones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reunion_historial', schema=None) as batch_op:
        batch_op.create_index('ix_reunion_historial_reunion', ['reunion_id', 'changed_at'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_event_id', sa.Integer(), nullable=False),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=True),
    sa.Column('enviado_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("resultado IN ('enviado', 'fallido')", name='ck_email_log_resultado'),
    sa.ForeignKeyConstraint(['email_event_id'], ['email_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)

    with op.batch_alter_table('logs_sistema', schema=None) as batch_op:
        batch_op.alter_column('rol_actor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index('ix_notification_event_programado', ['estado', 'programado_para'], unique=False)

    with op.batch_alter_table('reuniones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_reunion_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_reuniones_responsable', ['responsable_reunion_id'], unique=False)
        batch_op.create_foreign_key('fk_reuniones_responsable_reunion_id', 'usuarios', ['responsable_reunion_id'], ['id'])

    op.execute("UPDATE reuniones SET responsable_reunion_id = creador_id WHERE responsable_reunion_id IS NULL")
    with op.batch_alter_table('reuniones', schema=None) as batch_op:
        batch_op.alter_column('responsable_reunion_id', existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)

    op.execute("UPDATE roles SET nombre = 'Administrador del sistema' WHERE nombre = 'Admin'")
    op.execute("UPDATE roles SET nombre = 'Secretaria' WHERE nombre = 'Agendador'")
    op.execute("UPDATE roles SET nombre = 'Colaborador' WHERE nombre = 'Usuario natural'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('reuniones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reuniones_responsable_reunion_id', type_='foreignkey')
        batch_op.drop_index('ix_reuniones_responsable')
        batch_op.drop_column('responsable_reunion_id')

    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_event_programado')

    with op.batch_alter_table('logs_sistema', schema=None) as batch_op:
        batch_op.alter_column('rol_actor',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('configuracion', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.drop_table('email_logs')
    with op.batch_alter_table('reunion_historial', schema=None) as batch_op:
        batch_op.drop_index('ix_reunion_historial_reunion')

    op.drop_table('reunion_historial')
    with op.batch_alter_table('email_events', schema=None) as batch_op:
        batch_op.drop_index('ix_email_event_programado')

    op.drop_table('email_events')
    # ### end Alembic commands ###
